/** This is the answer schema to save the answers
 *  questionID   --- generated by mongo
 *  answerIndex  --- Index of the choosen radio button
 *  question     --- Question Text
 *  answer       --- Answer value
 */

const mongoose = require("mongoose");

const answerSchema = new mongoose.Schema({
  questionId: { type: mongoose.Schema.Types.ObjectId },
  answerIndex: { type: Number },
  question: { type: String },
  answer: { type: Array }
});

module.exports = new mongoose.model("answers", answerSchema);
